version: "3.9"
services:
        wp:
                build: .
                hostname: wordpress
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - ./src:/var/www/html/wp-content/plugins/hortadav
                        - /var/log:/var/log
                links:
                        - db
                depends_on:
                        - db
                environment:
                        WORDPRESS_DB_HOST: db
                        WORDPRESS_DB_USER: wpuser
                        WORDPRESS_DB_PASSWORD: wppwd
                        WORDPRESS_DB_NAME: wordpress
                        WORDPRESS_TABLE_PREFIX: wp_
                        WORDPRESS_DEBUG: 1
        db:
                image: mariadb
                hostname: mariad
                ports:
                        - "3306:3306"
                volumes:
                        - ./.db:/var/lib/mysql
                        - /var/log:/var/log
                environment:
                        MARIADB_ROOT_PASSWORD: root
                        MARIADB_DATABASE: wordpress
                        MARIADB_USER: wpuser
                        MARIADB_PASSWORD: wppwd
