<?php
return ['project-id-version'=>'HortaDAV 1.0.0','report-msgid-bugs-to'=>'https://wordpress.org/support/plugin/hortadav','last-translator'=>'','language-team'=>'Spanish (Spain)','mime-version'=>'1.0','content-type'=>'text/plain; charset=UTF-8','content-transfer-encoding'=>'8bit','pot-creation-date'=>'2025-02-09T20:49:40+00:00','po-revision-date'=>'2025-02-09 21:00+0000','x-generator'=>'Loco https://localise.biz/','x-domain'=>'hortadav','language'=>'es_ES','plural-forms'=>'nplurals=2; plural=n != 1;','x-loco-version'=>'2.7.1; wp-6.7.1','messages'=>['HortaDAV'=>'HortaDAV','https://github.com/codeccoop/hortadav'=>'https://github.com/codeccoop/hortadav','Exportació dels esdeveniments del calendari de sembra d\'hortalises compatible amb sistemes CalDAV'=>'Exportación de los eventos del calendario de siembra de hortalizas compatible con el sistema CalDAV','codeccoop'=>'codeccoop','https://www.codeccoop.org'=>'https://www.codeccoop.org','Calendari de l\'Hort'=>'Calendario del Huerto','Benvinguda al calendari de cultius de l\'hort. Aquí podràs trobar informació d\'algunes de les plantes que pots
tenir plantades al teu hort. <b>Utilitza el selector per visualitzar aquelles plantes que vulguis conèixer</b>.
Un cop tinguis seleccionades totes les que t\'interessin, navegant pel calendari podràs consultar quines són
les èpoques de plantació, floració i collita de cada espècie. Finalment, fent clic al botó <b>"Descarregar"</b>,
podràs obtenir un arxiu per importar a l\'aplicació de calendari que desitgis i endur-te aquesta informació
al teu calendari personal.'=>'Bienvenida al calendario de cultivos del huerto. Aquí podrás encontrar información dee algunas de las plantas que puedes
tener plantadas en tu huerto. <b>Utiliza el selector para visualizar aquellas plantas que quieras conocer</b>.
Una vez tengas seleccionadas todas las que te interesen, navegando por el calendario podrás consultar cuales son
las épocas de plantación, floración y recoleccion de cada especie. Finalmente, haciendo clic en el botón <b>"Descargar"</b>,
podrás obtener un fichero para importar a la aplicación de calendario que desees y llevarte esta información
a tu calendario personal.','Calendari de l\'hort'=>'Calendario del huerto','Esdeveniment de l\'hort'=>'Evento del  huerto','Esdeveniment del calendari de llaura i sembra'=>'Evento del calendario de labra y siembra','Famílies'=>'Familias','Familia'=>'Familia','Cicles de vida'=>'Ciclos de vida','Cicle de vida'=>'Ciclo de vida','Profunditats de sembra'=>'Profundidades de siembra','Profunditat de sembra'=>'Profundidad de siembra','Temps de germinació o brotació'=>'Tiempo de germinación o brotación','Durades fins a recol·lecció'=>'Duradas hasta la recolección','Durada fins a recol·lecció'=>'Durada hasta la recolección','Marcs de plantació'=>'Marcos de plantación','Marc de plantació'=>'Marco de plantación','Localitzacions'=>'Localizaciones','Localització'=>'Localización','Error al crear el terme %s a la taxonomia %s'=>'Error al crear el término %s en la taxonomía %s','Calendari'=>'Calendario','Les plantes de l\'hort'=>'Las plantas del huerto','Neteja'=>'Limpieza','Descarrega'=>'Descarga']];
