<?php
return ['project-id-version'=>'HortaDAV 1.0.0','report-msgid-bugs-to'=>'https://wordpress.org/support/plugin/hortadav','last-translator'=>'','language-team'=>'Catalan','mime-version'=>'1.0','content-type'=>'text/plain; charset=UTF-8','content-transfer-encoding'=>'8bit','pot-creation-date'=>'2025-02-09T20:49:40+00:00','po-revision-date'=>'2025-02-09 20:54+0000','x-generator'=>'Loco https://localise.biz/','x-domain'=>'hortadav','language'=>'ca','plural-forms'=>'nplurals=2; plural=n != 1;','x-loco-version'=>'2.7.1; wp-6.7.1','messages'=>['HortaDAV'=>'HortaDAV','https://github.com/codeccoop/hortadav'=>'https://github.com/codeccoop/hortadav','Exportació dels esdeveniments del calendari de sembra d\'hortalises compatible amb sistemes CalDAV'=>'Exportació dels esdeveniments del calendari de sembra d\'hortalises compatible amb sistemes CalDAV','codeccoop'=>'codeccoop','https://www.codeccoop.org'=>'https://www.codeccoop.org','Calendari de l\'Hort'=>'Calendari de l\'Hort','Benvinguda al calendari de cultius de l\'hort. Aquí podràs trobar informació d\'algunes de les plantes que pots
tenir plantades al teu hort. <b>Utilitza el selector per visualitzar aquelles plantes que vulguis conèixer</b>.
Un cop tinguis seleccionades totes les que t\'interessin, navegant pel calendari podràs consultar quines són
les èpoques de plantació, floració i collita de cada espècie. Finalment, fent clic al botó <b>"Descarregar"</b>,
podràs obtenir un arxiu per importar a l\'aplicació de calendari que desitgis i endur-te aquesta informació
al teu calendari personal.'=>'Benvinguda al calendari de cultius de l\'hort. Aquí podràs trobar informació d\'algunes de les plantes que pots
tenir plantades al teu hort. <b>Utilitza el selector per visualitzar aquelles plantes que vulguis conèixer</b>.
Un cop tinguis seleccionades totes les que t\'interessin, navegant pel calendari podràs consultar quines són
les èpoques de plantació, floració i collita de cada espècie. Finalment, fent clic al botó <b>"Descarregar"</b>,
podràs obtenir un arxiu per importar a l\'aplicació de calendari que desitgis i endur-te aquesta informació
al teu calendari personal.','Calendari de l\'hort'=>'Calendari de l\'hort','Esdeveniment de l\'hort'=>'Esdeveniment de l\'hort','Esdeveniment del calendari de llaura i sembra'=>'Esdeveniment del calendari de llaura i sembra','Famílies'=>'Famílies','Familia'=>'Familia','Cicles de vida'=>'Cicles de vida','Cicle de vida'=>'Cicle de vida','Profunditats de sembra'=>'Profunditats de sembra','Profunditat de sembra'=>'Profunditat de sembra','Temps de germinació o brotació'=>'Temps de germinació o brotació','Durades fins a recol·lecció'=>'Durades fins a recol·lecció','Durada fins a recol·lecció'=>'Durada fins a recol·lecció','Marcs de plantació'=>'Marcs de plantació','Marc de plantació'=>'Marc de plantació','Localitzacions'=>'Localitzacions','Localització'=>'Localització','Error al crear el terme %s a la taxonomia %s'=>'Error al crear el terme %s a la taxonomia %s','Calendari'=>'Calendari','Les plantes de l\'hort'=>'Les plantes de l\'hort','Neteja'=>'Neteja','Descarrega'=>'Descarrega']];
